### ISSUE TITLE
Discussion typography and more

### ISSUE THREAD

**Issue by KhenBai** [hexason/hexason_main#38]
Here we will discuss about how to implement our topography

- Sizes
- Fonts
- variants
- etx

**Comment by KhenBai** [comment]
<img width="166" alt="Screenshot 2023-05-30 at 03 21 35" src="https://github.com/cybinon/hexason/assets/56099382/da85e143-beae-4a33-994f-76348b8e6afc">
Starter text variants. Let's discuss variants first then we can use them like ==> title for Main titles, body2Aplha for semi-transparent text, etc. Then we can modify and update our font size and font-weight freely

**Comment by cybinon** [comment]
I guessing. Price is unique typography.

In Taobao, They highlighted prices using color. Maybe They're confident about product prices. But in Amazon all is different. They highlighted sale prices. Because the sale is important all of the customers.
Conclusion: We need to use a **price** and **sale** variant.

![image](https://github.com/cybinon/hexason/assets/56419470/bce10138-6190-422c-89a1-05cd4cc7f186)

**Comment by cybinon** [comment]
I read [Best 20 Fonts for e-commerce.](https://www.glorify.com/learn/20-best-fonts-for-ecommerce-businesses-brands-to-stand-out
)

The first 4 fonts are very standard and very clear in my eye. Specially Roboto font-based poster is very friendly to me. So our platform behavior is friendly and very clear most commonly use Roboto. Other fonts are based on suppliers. Anyways this is what I'm thinking nothing more XD

![image](https://github.com/cybinon/hexason/assets/56419470/509ceade-aa66-4bef-9a8d-e7fb7405d879)

**Comment by cybinon** [comment]
About `Size` I have no experience and nothing in my mind.

**Comment by cybinon** [comment]
@KhenBai  that's all. I hope it will be helpful. If I get any updates. I will notify.

**Comment by cybinon** [comment]
https://github.com/orgs/hexason/discussions/72
